.TH "Riferimenti per la directory /mnt/c/Users/stefa/Desktop/system_call/src" 3 "Mer 27 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Riferimenti per la directory /mnt/c/Users/stefa/Desktop/system_call/src
.SH SYNOPSIS
.br
.PP
.SS "File"

.in +1c
.ti -1c
.RI "file \fBclient\&.c\fP"
.br
.RI "Contiene l'implementazione del client\&. "
.ti -1c
.RI "file \fBclient\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche del CLIENT\&. "
.ti -1c
.RI "file \fBdebug\&.c\fP"
.br
.RI "Contiene l'implementazione delle funzioni per il debugging\&. "
.ti -1c
.RI "file \fBdebug\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni per il debugging\&. "
.ti -1c
.RI "file \fBdefines\&.c\fP"
.br
.RI "Contiene l'implementazione delle funzioni specifiche del progetto\&. "
.ti -1c
.RI "file \fBdefines\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche del progetto\&. "
.ti -1c
.RI "file \fBerr_exit\&.c\fP"
.br
.RI "Contiene l'implementazione della funzione di stampa degli errori\&. "
.ti -1c
.RI "file \fBerr_exit\&.h\fP"
.br
.RI "Contiene la definizione della funzione di stampa degli errori\&. "
.ti -1c
.RI "file \fBfifo\&.c\fP"
.br
.RI "Contiene l'implementazione delle funzioni specifiche per la gestione delle FIFO\&. "
.ti -1c
.RI "file \fBfifo\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche per la gestione delle FIFO\&. "
.ti -1c
.RI "file \fBfiles\&.c\fP"
.br
.RI "Contiene le funzioni specifiche per la gestione dei FILE\&. "
.ti -1c
.RI "file \fBfiles\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche per la gestione dei FILE\&. "
.ti -1c
.RI "file \fBsemaphore\&.c\fP"
.br
.RI "Contiene l'implementazione delle funzioni specifiche per la gestione dei SEMAFORI\&. "
.ti -1c
.RI "file \fBsemaphore\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche per la gestione dei SEMAFORI\&. "
.ti -1c
.RI "file \fBserver\&.c\fP"
.br
.RI "Contiene l'implementazione del server\&. "
.ti -1c
.RI "file \fBshared_memory\&.c\fP"
.br
.RI "Contiene l'implementazione delle funzioni specifiche per la gestione della MEMORIA CONDIVISA\&. "
.ti -1c
.RI "file \fBshared_memory\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche per la gestione della MEMORIA CONDIVISA\&. "
.ti -1c
.RI "file \fBsignals\&.c\fP"
.br
.RI "Contiene le funzioni specifiche per la gestione dei SEGNALI\&. "
.ti -1c
.RI "file \fBsignals\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche per la gestione dei SEGNALI\&. "
.ti -1c
.RI "file \fBstrings\&.c\fP"
.br
.RI "Contiene le funzioni specifiche per la gestione delle STRINGHE\&. "
.ti -1c
.RI "file \fBstrings\&.h\fP"
.br
.RI "Contiene la definizioni di variabili e funzioni specifiche per la gestione delle STRINGHE\&. "
.in -1c
