.TH "/mnt/c/Users/stefa/Desktop/system_call/src/debug.c" 3 "Sab 23 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/debug.c \- Contiene l'implementazione delle funzioni per il debugging\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'debug\&.h'\fP
.br

.SH "Descrizione dettagliata"
.PP 
Contiene l'implementazione delle funzioni per il debugging\&. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
