.TH "/mnt/c/Users/stefa/Desktop/system_call/src/defines.h" 3 "Sab 2 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/defines.h \- Contiene la definizioni di variabili e funzioni specifiche del progetto\&.  

.SH SYNOPSIS
.br
.PP
.SS "Definizioni"

.in +1c
.ti -1c
.RI "#define \fBBUFFER_SZ\fP   255"
.br
.RI "Buffer usato da getcwd() "
.ti -1c
.RI "#define \fBMSG_MAX_SZ\fP   4096"
.br
.RI "dimensione massima del messaggio/file da inviare "
.ti -1c
.RI "#define \fBMSG_PARTS_NUM\fP   4"
.br
.RI "numero parti in cui suddividere il messaggio "
.ti -1c
.RI "#define \fBMSG_BUFFER_SZ\fP   (\fBMSG_MAX_SZ\fP / \fBMSG_PARTS_NUM\fP)"
.br
.RI "dimensione massima di una porzione di messaggio "
.in -1c
.SH "Descrizione dettagliata"
.PP 
Contiene la definizioni di variabili e funzioni specifiche del progetto\&. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
