.TH "/mnt/c/Users/stefa/Desktop/system_call/src/defines.c" 3 "Sab 2 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/defines.c \- Contiene l'implementazione delle funzioni specifiche del progetto\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'defines\&.h'\fP
.br

.SH "Descrizione dettagliata"
.PP 
Contiene l'implementazione delle funzioni specifiche del progetto\&. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
