.TH "/mnt/c/Users/stefa/Desktop/system_call/src/err_exit.h" 3 "Sab 23 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/err_exit.h \- Contiene la definizione della funzione di stampa degli errori\&.  

.SH SYNOPSIS
.br
.PP
.SS "Funzioni"

.in +1c
.ti -1c
.RI "void \fBErrExit\fP (const char *msg)"
.br
.RI "Prints the error message of the last failed system call and terminates the calling process\&. "
.in -1c
.SH "Descrizione dettagliata"
.PP 
Contiene la definizione della funzione di stampa degli errori\&. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
