.TH "/mnt/c/Users/stefa/Desktop/system_call/src/fifo.c" 3 "Ven 1 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/fifo.c \- Contiene l'implementazione delle funzioni specifiche per la gestione delle FIFO\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'err_exit\&.h'\fP
.br
\fC#include 'fifo\&.h'\fP
.br

.SH "Descrizione dettagliata"
.PP 
Contiene l'implementazione delle funzioni specifiche per la gestione delle FIFO\&. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
