.TH "/mnt/c/Users/stefa/Desktop/system_call/src/fifo.h" 3 "Dom 3 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/fifo.h \- Contiene la definizioni di variabili e funzioni specifiche per la gestione delle FIFO\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descrizione dettagliata"
.PP 
Contiene la definizioni di variabili e funzioni specifiche per la gestione delle FIFO\&. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
