.TH "files_list" 3 "Gio 5 Mag 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
files_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <files\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "char * \fBpath\fP"
.br
.RI "Percorso file\&. "
.ti -1c
.RI "struct \fBfiles_list\fP * \fBnext\fP"
.br
.RI "Puntatore al prossimo nodo\&. "
.in -1c
.SH "Descrizione dettagliata"
.PP 
Nodo di una lista concatenata di filePath\&. 

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
