.TH "semun" 3 "Mar 21 Giu 2022" "Version 1.0.0" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semun
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "struct semid_ds * \fBbuf\fP"
.br
.ti -1c
.RI "unsigned short * \fBarray\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Union usata dalla system call semctl()\&. 
.SH "Documentazione dei campi"
.PP 
.SS "unsigned short * semun::array"
per eseguire operazioni su tutti i semafori\&. Usato dalle operazioni GETALL e SETALL 
.SS "struct semid_ds * semun::buf"
usato per lavorare sullo stato globale del semaforo\&. Usato dalle operazioni IPC_STAT e IPC_SET 
.SS "int semun::val"
usato se si lavora su un singolo semaforo\&. Usato dalla operazione SETVAL 

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
