.TH "semun" 3 "Sab 2 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semun
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <semaphore\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "struct semid_ds * \fBbuf\fP"
.br
.ti -1c
.RI "unsigned short * \fBarray\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 

.PP
\fBDa fare\fP
.RS 4
Commentare la union semun e i suoi attributi\&. 
.RE
.PP


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
