.TH "/mnt/c/Users/stefa/Desktop/system_call/src/server.c" 3 "Sab 9 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/server.c \- Contiene l'implementazione del server\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'err_exit\&.h'\fP
.br
\fC#include 'defines\&.h'\fP
.br
\fC#include 'shared_memory\&.h'\fP
.br
\fC#include 'semaphore\&.h'\fP
.br
\fC#include 'fifo\&.h'\fP
.br
\fC#include 'debug\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "void \fBSIGINTSignalHandler\fP (int sig)"
.br
.RI "Chiude tutte le IPC e termina\&. "
.ti -1c
.RI "int \fBstring_to_int\fP (char *string)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "char \fBEXECUTABLE_DIR\fP [\fBBUFFER_SZ\fP]"
.br
.RI "Percorso cartella eseguibile\&. "
.ti -1c
.RI "int \fBfifo1_fd\fP"
.br
.ti -1c
.RI "int \fBsemid\fP"
.br
.ti -1c
.RI "int \fBshmid\fP"
.br
.ti -1c
.RI "\fBmsg_t\fP * \fBshm_ptr\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Contiene l'implementazione del server\&. 


.SH "Documentazione delle funzioni"
.PP 
.SS "int main (int argc, char * argv[])"
ANNOTAZIONE: Probabilmente bisogna fare un ciclo per aspettare ogni file\&. Per ogni file bisogna attendere le 4 parti e poi scriverle su file in ordine\&.
.PP
terminazione effettuata con SIGINT: Al termine chiudi tutte le IPC\&. 
.SS "void SIGINTSignalHandler (int sig)"

.PP
Chiude tutte le IPC e termina\&. Handler del segnale SIGINT\&.
.PP
\fBParametri:\fP
.RS 4
\fIsig\fP 
.RE
.PP

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
