.TH "/mnt/c/Users/stefa/Desktop/system_call/src/shared_memory.h" 3 "Ven 1 Apr 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/c/Users/stefa/Desktop/system_call/src/shared_memory.h \- Contiene la definizioni di variabili e funzioni specifiche per la gestione della MEMORIA CONDIVISA\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descrizione dettagliata"
.PP 
Contiene la definizioni di variabili e funzioni specifiche per la gestione della MEMORIA CONDIVISA\&. 


.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SYSTEM_CALL a partire dal codice sorgente\&.
