.TH "warning" 3 "Gio 5 Mag 2022" "Version 0.0.1" "SYSTEM_CALL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
warningWarnings 
 \- 
.IP "\fBGlobale \fBmain\fP (int argc, char *argv[])\fP" 1c
I file devono essere riuniti appena vengono ricevuti i 4 pezzi oppure va bene riunirli alla fine?  
.IP "\fBGlobale \fBoperazioni_client0\fP ()\fP" 1c
Per ottimizzare l'uso dello HEAP nel client 0 si potrebbe prima cercare e contare quanti file sono presenti senza creare una lista concatenata e poi ricercare i file e man mano che si trovano file send_me si puo' creare il processo figlio per inviare il file\&. Per fare questo BISOGNA sapere se il numero di file puo' cambiare durante l'esecuzione di questa funzione: se trovo 3 file e dopo un file viene cancellato cosa succede? 
.br
 NOTA: questo problema puo' esserci anche nella situazione attuale\&.\&.\&.
.PP
Il client 0 deve attendere i processi figlio? La specifica indica solo che bisogna attendere il messaggio di fine dal server\&.\&.\&. Attualmente prima si attendere il messaggio di fine e poi si aspetta che tutti i figlio terminino\&.
.PP
Il percorso passato al client deve essere assoluto o puo' essere relativo? Se si passa un percorso relativo chdir() fallira' alla seconda esecuzione\&. 
.br
 SOLUZIONE: si potrebbe usare un altro chdir() a fine funzione per tornare al percorso di esecuzione iniziale anticipando il chdir() successivo\&.
.PP

