name: E2E verify output debug

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip install psutil==5.9.0

    - name: run E2E test
      run: |
        cd tests/end2end
        python3 test_end2end.py --verify-debug
